name: 'SSH Connection'
description: 'GitHub SSH Connection Action'

inputs:
  password:
    description: 'SSH password'
    required: true
    
  host:
    description: 'SSH host (server IP)'
    required: true
    
  username:
    description: 'SSH username'
    required: true
    
  port:
    description: 'SSH Port'
    required: true
    
  command:
    description: 'Shell Command'
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  
